# Generated by Django 4.2.2 on 2023-06-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songreview',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, '1/10'), (2, '2/10'), (3, '3/10'), (4, '4/10'), (5, '5/10'), (6, '6/10'), (7, '7/10'), (8, '8/10'), (9, '9/10'), (10, '10/10')], default=5, verbose_name='score'),
        ),
    ]
