# Generated by Django 4.2.2 on 2023-06-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_api', '0002_alter_songreview_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='songs/pictures', verbose_name='picture'),
        ),
    ]
